In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import sys

import datetime
import pandas as pd
from dateutil import relativedelta  
# from Codes.FRAIS import *

secto_reco_path = r"\\groupe-ufg.com\Commun\Prive\GestionAM\Ingenierie_Financiere\PROD\_EQUITY\0_PTF_BLOOM\reco_secto_facto.xlsx"
list_noire_path = r"\\groupe-ufg.com\Commun\Prive\GestionAM\Ingenierie_Financiere\PROD\_BASE\_ ESG DATA\Liste_Noire_Exclusion.xlsx"

path_screen = r"C:\GoogleDrive\TP\screen\screen_aggregate.pkl"
path_returns = r"C:\GoogleDrive\TP\screen\returns.pkl"

<div style="background-color: #013220; color: white; padding: 10px;">
    <h1> Generation Score ML</h1>
</div>

### EUROPE

In [3]:
from Codes.ML_PIPELINE import ML_MonthlyProdPipeline

import Config.config_EU as config
predictor = ML_MonthlyProdPipeline(  
    config.CONFIG,  
    mode="backtest",
    preprocessing=True,
    update_score_ML=True,
    allow_multiprocessing=False,
    output_path=r"Output_files\\",
    output_file="SCORE_ML_EU"
)  

predictor.run()

Start of Preprocressing : (5 min)
max ecart entre 2 dates :  31.0
min ecart entre 2 dates :  28.0
TEST : detect_if_error_date REUSSI
New Compute Return 3.0started

New Compute Return 6.0started

End of Preprocressing.
The preprocessing file is saved at : Input_files\screen_ML_EU.pkl
Debut REPRISE SCORE
Period to predict is : [3.0, 6.0]
Output will be saved at Output_files\\SCORE_ML_EU
PRED_2
Period to predict is 3.0M
Number of batches to predict is : 80
No multi processing, sequential method is used for generating backtest...

Generating Backtest: 100%|██████████| 80/80 [29:29<00:00, 22.12s/parameter]

Period to predict is 6.0M
Number of batches to predict is : 77
No multi processing, sequential method is used for generating backtest...

Generating Backtest: 100%|██████████| 77/77 [23:27<00:00, 18.27s/parameter]

homogenous_mean_and_rank
Backtesting completed. Results saved to Output_files\\SCORE_ML_EU.pkl
Backtesting completed. Results saved to Output_files\\SCORE_ML_EU_SHAP.pkl

,Date,Company SEDOL,index,Symbol,Name,Exchange Country Name,FactSet Ind,FactSet Economy,Curncy Iso,Region,...,Sector 18,Sector 19,3.0M label,6.0M label,3.0M y_pred,6.0M y_pred,3.0M y_pred_scaled,6.0M y_pred_scaled,average_prediction,Score ML
ISIN,,,,,,,,,,,,,,,,,,,,,
AT0000606306,2019-06-30,S0YJ3Z-R,63,S0YJ3Z-R,Raiffeisen Bank International AG,AUSTRIA,Major Banks,FINANCE,EUR,West Europe,...,False,False,0.032792,-0.000307,0.000162,0.004192,0.000054,0.000699,0.000376,4.316667
AT0000606306,2019-07-31,S0YJ3Z-R,64,S0YJ3Z-R,Raiffeisen Bank International AG,AUSTRIA,Major Banks,FINANCE,EUR,West Europe,...,False,False,-0.001790,-0.068803,-0.005922,-0.007517,-0.001974,-0.001253,-0.001613,1.651706
AT0000606306,2019-08-31,S0YJ3Z-R,65,S0YJ3Z-R,Raiffeisen Bank International AG,AUSTRIA,Major Banks,FINANCE,EUR,West Europe,...,False,False,-0.058292,-0.075936,0.001292,0.002746,0.000431,0.000458,0.000444,4.685817
AT0000606306,2019-09-30,S0YJ3Z-R,66,S0YJ3Z-R,Raiffeisen Bank International AG,AUSTRIA,Major Banks,FINANCE,EUR,West Europe,...,False,False,-0.035539,-0.033416,0.012356,0.012960,0.004119,0.002160,0.003139,8.313856
AT0000606306,2019-10-31,S0YJ3Z-R,67,S0YJ3Z-R,Raiffeisen Bank International AG,AUSTRIA,Major Banks,FINANCE,EUR,West Europe,...,False,False,-0.070211,0.030953,0.010674,0.011077,0.003558,0.001846,0.002702,8.061041
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ZAE000255360,2020-04-30,L5JGFL-R,82900,L5JGFL-R,Old Mutual Ltd.,SOUTH AFRICA,Life/Health Insurance,FINANCE,ZAR,Africa,...,False,False,NaN,NaN,0.001007,0.008332,0.000336,0.001389,0.000862,5.782918
ZAE000255360,2020-05-31,L5JGFL-R,82901,L5JGFL-R,Old Mutual Ltd.,SOUTH AFRICA,Life/Health Insurance,FINANCE,ZAR,Africa,...,False,False,NaN,NaN,0.002689,0.008133,0.000896,0.001355,0.001126,6.316726
ZAE000255360,2020-06-30,L5JGFL-R,82902,L5JGFL-R,Old Mutual Ltd.,SOUTH AFRICA,Life/Health Insurance,FINANCE,ZAR,Africa,...,False,False,NaN,NaN,-0.014535,-0.010122,-0.004845,-0.001687,-0.003266,1.154529
ZAE000255360,2020-07-31,L5JGFL-R,82903,L5JGFL-R,Old Mutual Ltd.,SOUTH AFRICA,Life/Health Insurance,FINANCE,ZAR,Africa,...,False,False,NaN,NaN,-0.011322,-0.011587,-0.003774,-0.001931,-0.002853,1.207815
ZAE000255360,2020-08-31,L5JGFL-R,82904,L5JGFL-R,Old Mutual Ltd.,SOUTH AFRICA,Life/Health Insurance,FINANCE,ZAR,Africa,...,False,False,NaN,NaN,-0.010486,-0.012301,-0.003495,-0.002050,-0.002773,1.296625

### US

In [4]:
from Codes.ML_PIPELINE import ML_MonthlyProdPipeline

import Config.config_US as config
predictor = ML_MonthlyProdPipeline(  
    config.CONFIG,  
    mode="backtest",
    preprocessing=True,
    update_score_ML=True,
    allow_multiprocessing=False,
    output_path=r"Output_files\\",
    output_file="SCORE_ML_US"
)  

predictor.run()

Start of Preprocressing : (5 min)
max ecart entre 2 dates :  31.0
min ecart entre 2 dates :  28.0
TEST : detect_if_error_date REUSSI
New Compute Return 3.0started

New Compute Return 6.0started

End of Preprocressing.
The preprocessing file is saved at : Input_files\screen_ML_US.pkl
Debut REPRISE SCORE
Period to predict is : [3.0, 6.0]
Output will be saved at Output_files\\SCORE_ML_US
PRED_2
Period to predict is 3.0M
Number of batches to predict is : 80
No multi processing, sequential method is used for generating backtest...

Generating Backtest: 100%|██████████| 80/80 [26:21<00:00, 19.76s/parameter]

Period to predict is 6.0M
Number of batches to predict is : 77
No multi processing, sequential method is used for generating backtest...

Generating Backtest: 100%|██████████| 77/77 [24:53<00:00, 19.40s/parameter]

homogenous_mean_and_rank
Backtesting completed. Results saved to Output_files\\SCORE_ML_US.pkl
Backtesting completed. Results saved to Output_files\\SCORE_ML_US_SHAP.pkl

,Date,Company SEDOL,index,Symbol,Name,Exchange Country Name,FactSet Ind,FactSet Economy,Curncy Iso,Region,...,Sector 18,Sector 19,3.0M label,6.0M label,3.0M y_pred,6.0M y_pred,3.0M y_pred_scaled,6.0M y_pred_scaled,average_prediction,Score ML
ISIN,,,,,,,,,,,,,,,,,,,,,
AN8068571086,2019-06-30,BJ2HRV-R,66,SLB,SLB Limited,UNITED STATES,Contract Drilling,INDUSTRIALS,USD,North America,...,False,False,-0.062949,0.049529,-0.031883,-0.044185,-0.010628,-0.007364,-0.008996,0.992063
AN8068571086,2019-07-31,BJ2HRV-R,67,SLB,SLB Limited,UNITED STATES,Contract Drilling,INDUSTRIALS,USD,North America,...,False,False,-0.095550,-0.032091,-0.032831,-0.028061,-0.010944,-0.004677,-0.007810,0.983607
AN8068571086,2019-08-31,BJ2HRV-R,68,SLB,SLB Limited,UNITED STATES,Contract Drilling,INDUSTRIALS,USD,North America,...,False,False,0.093012,0.032393,-0.032479,-0.026956,-0.010826,-0.004493,-0.007659,0.942623
AN8068571086,2019-09-30,BJ2HRV-R,69,SLB,SLB Limited,UNITED STATES,Contract Drilling,INDUSTRIALS,USD,North America,...,False,False,0.126065,-0.106028,-0.051171,-0.051656,-0.017057,-0.008609,-0.012833,0.396825
AN8068571086,2019-10-31,BJ2HRV-R,70,SLB,SLB Limited,UNITED STATES,Contract Drilling,INDUSTRIALS,USD,North America,...,False,False,0.071817,-0.153861,-0.041374,-0.050702,-0.013791,-0.008450,-0.011121,0.553279
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ZAE000138459,2019-07-31,J9DRN6-R,70495,J9DRN6-R,Sephaku Holdings Limited,SOUTH AFRICA,Construction Materials,BASIC MATERIALS,ZAR,Africa,...,False,False,NaN,NaN,-0.038402,-0.072487,-0.012801,-0.012081,-0.012441,0.430328
ZAE000138459,2019-08-31,J9DRN6-R,70496,J9DRN6-R,Sephaku Holdings Limited,SOUTH AFRICA,Construction Materials,BASIC MATERIALS,ZAR,Africa,...,False,False,NaN,NaN,-0.038817,-0.059075,-0.012939,-0.009846,-0.011392,0.573770
ZAE000138459,2019-12-31,J9DRN6-R,70497,J9DRN6-R,Sephaku Holdings Limited,SOUTH AFRICA,Construction Materials,BASIC MATERIALS,ZAR,Africa,...,False,False,NaN,NaN,-0.034769,-0.068881,-0.011590,-0.011480,-0.011535,1.693878
ZAE000138459,2020-01-31,J9DRN6-R,70498,J9DRN6-R,Sephaku Holdings Limited,SOUTH AFRICA,Construction Materials,BASIC MATERIALS,ZAR,Africa,...,False,False,NaN,NaN,0.002999,0.004082,0.001000,0.000680,0.000840,5.367347
ZAE000138459,2020-02-29,J9DRN6-R,70499,J9DRN6-R,Sephaku Holdings Limited,SOUTH AFRICA,Construction Materials,BASIC MATERIALS,ZAR,Africa,...,False,False,-0.546605,-0.645675,-0.001029,-0.013191,-0.000343,-0.002199,-0.001271,4.714286

### OTHER

In [ ]:
screen_agg = pd.read_pickle(path_screen)

# We only want to invest in 3 countries in other region beside EU and US, and we don't want small cap so filter with 5000 
filtered_screen = screen_agg[~screen_agg['Exchange Country Region'].isin(['West Europe', 'North America', 'East Europe'])]  
filtered_screen = filtered_screen[
    (filtered_screen['Weight in MSCI ACWI']>0)&
    (filtered_screen['Benchmark Market Value Millions in EUR']>5000)&
    (filtered_screen['Exchange Country Name'].isin(["AUSTRALIA", 'SOUTH KOREA', 'JAPAN']))
    ]

# Building universe and save it locally
univ_other_countires = filtered_screen[filtered_screen['Weight in MSCI ACWI']>0]

univ_other_countires['Weight in MSCI ACWI'] = (
                                univ_other_countires.groupby("Date")['Weight in MSCI ACWI']
                                .transform(lambda x: x / x.sum())
                                )


univ_other_countires.to_pickle(r"Input_files\univ_OTHER.pkl")

In [ ]:
from Codes.ML_PIPELINE import ML_MonthlyProdPipeline

import Config.config_OTHER as config
predictor = ML_MonthlyProdPipeline(  
    config.CONFIG,  
    mode="backtest",
    preprocessing=True,
    update_score_ML=True,
    allow_multiprocessing=True,
    output_path=r"Output_files\\",
    output_file="SCORE_ML_OTHER"
)  

predictor.run()

<div style="background-color: #013220; color: white; padding: 10px;">
    <h1> Generation PTF and Backtest</h1>
</div>

### EUROPE

In [6]:
import pandas as pd
from Codes.BacktestEngine import *

path_screen = r"C:\GoogleDrive\TP\screen\screen_aggregate.pkl"
path_returns = r"C:\GoogleDrive\TP\screen\returns.pkl"

In [11]:
################ EUROPE ################
NAME = "EU"

#Input path 
screen_with_score_path = r"C:\GoogleDrive\TP\ML\Output_files\SCORE_ML_EU.pkl"

#Output path
ptf_save_path = rf"Portfolio_BT\PTF_ESG_{NAME}_semi.pkl"
perf_save_path = rf"Portfolio_BT\Perf_ESG_{NAME}_semi.pkl"

screen_agg_with_score = pd.read_pickle(screen_with_score_path)
returns = pd.read_pickle(path_returns) 

bench = 'STOXX EUROPE 600' #'STOXX EUROPE 600'
metrics = 'Score ML'
percentile = 0.05 # Top 600 * 0.10 = 60 boites
esg_exclusion = 0
ptf_name = 'ML EU Q1'
ponderation = "Equalweight" #'Market cap'
top_mandatory = None
cap_weight_threshold = None
cut_mkt_cap = 0

# pct_dev_secto = 3
# secto_eu = pd.read_excel(secto_reco_path, sheet_name="secto_eu", index_col=0)
# secto_eu = secto_eu/5 * pct_dev_secto


builder_EU = PtfBuilder(screen_agg_with_score, 
                    returns, 
                    bench=bench,
                    ptf_name=ptf_name, 
                    percentile=percentile,
                    esg_exclusion=esg_exclusion,
                    liste_noire=None,
                    metrics=metrics, 
                    ponderation = ponderation,
                    top_mandatory=top_mandatory,
                    cap_weight_threshold=cap_weight_threshold,
                    # reco_secto=secto_eu,
                    cut_mkt_cap = cut_mkt_cap)

builder_EU.generic_histo_seclist(start_date=screen_agg_with_score.dropna(subset=['Score ML'])['Date'].min(),freq_rebal=1, screen_start_date = "mois_impair")

# Copie du ptf precedent sur les dates manquantes
ptf = builder_EU.sec_list_historical.copy()        

# builder_EU.sec_list_historical.to_pickle(ptf_save_path)

builder_EU.backtest_plot_ptf_bench(save_path=False)

# builder_EU.perf_ptf.to_pickle(perf_save_path)

Premiere date du screen_agg prise en compte :  2019-07-31 00:00:00

Generating security lists: 100%|██████████| 76/76 [00:04<00:00, 17.18it/s]

Historical sec list is generated, you can check 'self.sec_list_historical' attribute for more details.
Historical exclusion list is generated, you can check 'self.list_exclusion' attribute for more details.
Performance of sec_list is calculated, please check attribute "self.perf_ptf" for more details
Performance of benchmark is calculated, please check attribute "self.perf_bench" for more details

### US

In [8]:
################ US ################
NAME = "US"

# Input path
screen_with_score_path = r"C:\GoogleDrive\TP\ML\Output_files\SCORE_ML_US.pkl"

#Output path
# ptf_save_path = rf"Portfolio_BT\PTF_ESG_{NAME}.pkl"
# perf_save_path = rf"Portfolio_BT\Perf_ESG_{NAME}.pkl"

screen_agg_with_score = pd.read_pickle(screen_with_score_path)
returns = pd.read_pickle(path_returns) 

bench='SP500'
metrics = 'Score ML'
percentile = 0.05
esg_exclusion = 0
ptf_name = 'ML US Q1'
ponderation = 'Market cap'  #'Market cap'
top_mandatory = None
cap_weight_threshold = None
cut_mkt_cap = None

# pct_dev_secto = 3
# secto_us = pd.read_excel(secto_reco_path, sheet_name="secto_us", index_col=0)
# secto_us = secto_us/5 * pct_dev_secto

builder_US = PtfBuilder(screen_agg_with_score, 
                    returns,
                    ptf_name=ptf_name, 
                    bench=bench, 
                    percentile=percentile,
                    esg_exclusion=esg_exclusion,
                    liste_noire=None,
                    ponderation = ponderation,
                    metrics=metrics, 
                    top_mandatory=top_mandatory,
                    cap_weight_threshold=cap_weight_threshold,
                    # reco_secto=secto_us,
                    cut_mkt_cap = cut_mkt_cap)

builder_US.generic_histo_seclist(start_date=screen_agg_with_score.dropna(subset=['Score ML'])['Date'].min(), freq_rebal=1, screen_start_date = "mois_impair")

# builder_US.sec_list_historical.to_pickle(ptf_save_path)


builder_US.backtest_plot_ptf_bench(save_path=False)

# builder_US.perf_ptf.to_pickle(perf_save_path)

Premiere date du screen_agg prise en compte :  2019-07-31 00:00:00

Generating security lists: 100%|██████████| 76/76 [00:04<00:00, 16.11it/s]

Historical sec list is generated, you can check 'self.sec_list_historical' attribute for more details.
Historical exclusion list is generated, you can check 'self.list_exclusion' attribute for more details.
Performance of sec_list is calculated, please check attribute "self.perf_ptf" for more details
Performance of benchmark is calculated, please check attribute "self.perf_bench" for more details

### Other

In [ ]:
################ EUROPE ################
NAME = "OTHER"

#Input path
screen_with_score_path = rf"Output_files\SCORE_ML_{NAME}.pkl"

#Output path
ptf_save_path = rf"Portfolio_BT\PTF_ESG_{NAME}.pkl"
perf_save_path = rf"Portfolio_BT\Perf_ESG_{NAME}.pkl"

screen_agg_with_score = pd.read_pickle(screen_with_score_path)
returns = pd.read_pickle(path_returns) 

bench='MSCI ACWI'
metrics = 'Score ML'
percentile = 0.15
esg_exclusion = 0.2
ponderation = 'Market cap'
ptf_name='ML OTHER Q1'
cap_weight_threshold = 0.065
cut_mkt_cap = 2000


builder_OTHER = PtfBuilder(screen_agg_with_score, 
                    returns,
                    ptf_name=ptf_name, 
                    bench=bench, 
                    percentile=percentile,
                    esg_exclusion=esg_exclusion,
                    ponderation= ponderation,
                    liste_noire=list_noire_path,
                    metrics=metrics, 
                    cap_weight_threshold=cap_weight_threshold,
                    cut_mkt_cap = cut_mkt_cap)

builder_OTHER.generic_histo_seclist(start_date=datetime.datetime(2010,2,1),freq_rebal=1, screen_start_date = "mois_impair")

builder_OTHER.sec_list_historical.to_pickle(ptf_save_path)

builder_OTHER.backtest_plot_ptf_bench(save_path=False)

builder_OTHER.perf_ptf.to_pickle(perf_save_path)

<div style="background-color: #013220; color: white; padding: 10px;">
    <h1> Rassemblage</h1>
</div>

In [ ]:


# PTF_EU = pd.read_pickle(r"Portfolio_BT\PTF_ESG_EU.pkl")
PTF_EU = pd.read_pickle(r"Portfolio_BT\PTF_ESG_EU_semi.pkl")
PTF_US = pd.read_pickle(r"Portfolio_BT\PTF_ESG_US.pkl")
PTF_OTHER = pd.read_pickle(r"Portfolio_BT\PTF_ESG_OTHER.pkl")

#Verifier qu'on a la meme dates
dates_sont_egales(PTF_EU,PTF_US, PTF_OTHER)

Les dates sont les mêmes

In [ ]:
returns = pd.read_pickle(path_returns) 
screen_agg = pd.read_pickle(path_screen)
screen_agg = screen_agg.reset_index()

In [ ]:

# POIDS REGIONAUX DANS ACWI 
weight_regions_acwi = (
screen_agg
.groupby('Date')
.apply(compute_weights_for_date_acwi)
)

# REBALANCE 100%
weight_regions_acwi = weight_regions_acwi.div(weight_regions_acwi.sum(axis=1), axis=0)

# POIDS REGIONAUX DANS MSCI WORLD after 2017
weight_regions_world = (
screen_agg[screen_agg['Date']>="2017-01-01"]
.groupby('Date')
.apply(compute_weights_for_date_world)
)

# REBALANCE 100%
weight_regions_world = weight_regions_world.div(weight_regions_world.sum(axis=1), axis=0)


# Replace weight after 2017 with MSCI WORLD data
weight_regions_acwi.loc[weight_regions_world.index, ['US weight', 'EU weight', 'Other weight']] = weight_regions_world[['US weight', 'EU weight', 'Other weight']]
weight_regions_bench = weight_regions_acwi.copy(deep=True)

# Align date of regional weight with date of ptf generated
weight_regions_bench.index = weight_regions_bench.index + pd.offsets.MonthBegin(1) # Both regional weight or ptf will have the first day of month as Date


# SOUS PONDERER OTHER DE 0.8
weight_regions_bench = adjust_weights_OTHER(weight_regions_bench, ratio_other=0.8)


us_adjusted = adjust_single_portfolio_weights(PTF_US, weight_regions_bench.reset_index(), 'US')
eu_adjusted = adjust_single_portfolio_weights(PTF_EU, weight_regions_bench.reset_index(), 'EU')
other_adjusted = adjust_single_portfolio_weights(PTF_OTHER, weight_regions_bench.reset_index(), 'Other')

ptf_world_semi = pd.concat([us_adjusted, eu_adjusted, other_adjusted], axis=0)
ptf_world_semi = ptf_world_semi[ptf_world_semi['Date'] >= "2010-03-01"]

# Rebalancing
ptf_world_semi['Weight'] = (
                    ptf_world_semi.groupby(["Date"])['Weight']
                    .transform(lambda w: w / w.sum())
                    )


world_ptf_save_path_pickle = r"Portfolio_BT\PTF_WORLD_semi.pkl"
ptf_world_semi.to_pickle(world_ptf_save_path_pickle)
world_ptf_save_path_excel = r"Portfolio_BT\PTF_WORLD_semi.xlsx"
ptf_world_semi.to_excel(world_ptf_save_path_excel)

perf_save_path = rf"Portfolio_BT\Perf_ESG_WORLD_semi.pkl"
bench = "MSCI ACWI"

perf_ptf_WORLD_semi, perf_bench_WORLD_semi, buy_list = generate_portfolio_performance(
    screen_agg, ptf_world_semi, bench, returns, perf_save_path
)

perf_WORLD_semi = normalize_to_base_100(pd.concat([perf_ptf_WORLD_semi, perf_bench_WORLD_semi], axis=1).dropna())

# Avec Frais

In [ ]:
# world_ptf_save_path_pickle = r"Portfolio_BT\PTF_WORLD_semi.pkl"
ptf_MSCI_W_rebal2mEurope = pd.read_pickle(world_ptf_save_path_pickle)
# screen_agg = screen_agg.set_index("ISIN")

In [ ]:
start_date = datetime.datetime(2010,1,1)
bench = '' #'SP500' #'MSCI WORLD'# bench_name


structure_cout_TTF=pd.DataFrame({"Country": ["FR","IT","GB","ES"],"Fees": [-0.004, -0.001,-0.005,-0.002]})
structure_cout_Table_Exe=-0.0001
structure_cout_Table_Broker=-0.0002
structure_cout_fdg=-0.00/365
structure_cout={"structure_cout_TTF":structure_cout_TTF,"structure_cout_Table_Exe":structure_cout_Table_Exe,"structure_cout_Table_Broker":structure_cout_Table_Broker,"structure_cout_fdg":structure_cout_fdg}
    
     
perf_ptf_semi, buy_list_semi, weight_change_semi, portfolio_tet_semi = backtest_with_frais(structure_cout, ptf_MSCI_W_rebal2mEurope, bench, screen_agg, returns)
perf_ptf_semi = perf_ptf_semi.set_index("Date")
perf_ptf_semi

,total_return_by_date,serie_ttr_gross,Date Rebalancing,TTF cost,Table cost,Broker cost,Turn_Over 2w,days_diff,frais de gestion,net_return_by_date,serie_total_nr,serie_cost,Turn-Over 2w cumsum
Date,,,,,,,,,,,,,
2010-07-01,0.000000,100.000000,NaT,0.0,0.0,0.0,0.0,NaN,0.0,0.000000,100.000000,100.000000,0.000000
2010-07-02,-0.008639,99.136127,NaT,0.0,0.0,0.0,0.0,1.0,-0.0,-0.008639,99.136127,100.000000,0.000000
2010-07-05,0.003277,99.461013,NaT,0.0,0.0,0.0,0.0,3.0,-0.0,0.003277,99.461013,100.000000,0.000000
2010-07-06,0.006824,100.139686,NaT,0.0,0.0,0.0,0.0,1.0,-0.0,0.006824,100.139686,100.000000,0.000000
2010-07-07,0.021876,102.330317,NaT,0.0,0.0,0.0,0.0,1.0,-0.0,0.021876,102.330317,100.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-08-18,0.004497,1298.675886,NaT,0.0,0.0,0.0,0.0,3.0,-0.0,0.004497,1219.020387,93.858323,136.738275
2025-08-19,-0.000299,1298.286950,NaT,0.0,0.0,0.0,0.0,1.0,-0.0,-0.000299,1218.655307,93.858323,136.738275
2025-08-20,-0.002878,1294.550330,NaT,0.0,0.0,0.0,0.0,1.0,-0.0,-0.002878,1215.147876,93.858323,136.738275
2025-08-21,0.001825,1296.912959,NaT,0.0,0.0,0.0,0.0,1.0,-0.0,0.001825,1217.365591,93.858323,136.738275
2025-08-22,0.006231,1304.994107,NaT,0.0,0.0,0.0,0.0,1.0,-0.0,0.006231,1224.951074,93.858323,136.738275

In [ ]:
df_portfoliosemi=pd.DataFrame()
perf_ptf_semi.index = perf_ptf_semi.index
df_portfoliosemi['Serie brut'] = perf_ptf_semi['serie_ttr_gross']
df_portfoliosemi['Serie net'] = perf_ptf_semi['serie_total_nr']
df_portfoliosemi['Bench'] = perf_bench_WORLD_semi[(perf_bench_WORLD_semi.index>=perf_ptf_semi.index[0])&(perf_bench_WORLD_semi.index<=perf_ptf_semi.index[-1])]
df_portfoliosemi_normalized = normalize_to_base_100(df_portfoliosemi)
df_portfoliosemi_normalized.to_excel("Portfolio_BT\Perf_ESG_WORLD_semi.xlsx")

In [ ]:
normalize_to_base_100(pd.concat([df_portfoliosemi[['Serie net']], df_portfoliosemi['Bench']], axis=1).dropna())
normalize_to_base_100(pd.concat([df_portfoliosemi[['Serie brut']], df_portfoliosemi['Bench']], axis=1).dropna())