In [2]:
%load_ext autoreload
%autoreload 2

In [1]:
from pathlib import Path

import datetime
import pandas as pd
from dateutil import relativedelta  
# from Codes.FRAIS import *

# secto_reco_path = r"\\groupe-ufg.com\Commun\Prive\GestionAM\Ingenierie_Financiere\PROD\_EQUITY\0_PTF_BLOOM\reco_secto_facto.xlsx"
# list_noire_path = r"\\groupe-ufg.com\Commun\Prive\GestionAM\Ingenierie_Financiere\PROD\_BASE\_ ESG DATA\Liste_Noire_Exclusion.xlsx"

from tp_core.data_sources import RETURNS_PATH as CANONICAL_RETURNS_PATH
from tp_core.data_sources import SCREEN_AGGREGATE_PATH

path_screen = str(SCREEN_AGGREGATE_PATH)
path_returns = str(CANONICAL_RETURNS_PATH)

from datetime import datetime
# 设置 max_date 为今天
today_str = datetime.today().strftime('%Y-%m-%d')

<div style="background-color: #013220; color: white; padding: 10px;">
    <h1> Generation Score ML</h1>
</div>

### EUROPE

In [3]:
from Codes.ML_PIPELINE import ML_MonthlyProdPipeline

import Config.config_EU as config
predictor = ML_MonthlyProdPipeline(  
    config.CONFIG,  
    mode="backtest",
    preprocessing=True,
    update_score_ML=True,
    allow_multiprocessing=True,
    output_path=r"Output_files\\",
    output_file="SCORE_ML_EU",
    max_date=today_str
)  

predictor.run()

ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

### US

In [3]:
from Codes.ML_PIPELINE import ML_MonthlyProdPipeline

import Config.config_US as config
predictor = ML_MonthlyProdPipeline(  
    config.CONFIG,  
    mode="backtest",
    preprocessing=False,
    update_score_ML=True,
    allow_multiprocessing=False,
    output_path=r"Output_files\\",
    output_file="SCORE_ML_US",
    max_date=today_str
)  

predictor.run()

Debut REPRISE SCORE
Period to predict is : [3.0, 6.0]
Output will be saved at Output_files\\SCORE_ML_US
PRED_2
Period to predict is 3.0M
Number of batches to predict is : 193
No multi processing, sequential method is used for generating backtest...

Backtest 3.0M: 0/193 |          | [00:00<?, ?batch/s]

Period to predict is 6.0M
Number of batches to predict is : 190
No multi processing, sequential method is used for generating backtest...

Backtest 6.0M: 0/190 |          | [00:00<?, ?batch/s]

homogenous_mean_and_rank
Backtesting completed. Results saved to Output_files\\SCORE_ML_US.parquet
Backtesting completed. Results saved to Output_files\\SCORE_ML_US_SHAP.parquet

,Date,Company SEDOL,index,Benchmark ICB Industry,Benchmark ICB Supersector,5Y_Hist EPS TrendStab,5Y_Hist GrossInc TrendStab,5Y_Hist Sales TrendStab,Asset TO exFIN,Benchmark Country English,...,Sector 18,Sector 19,3.0M label,6.0M label,3.0M y_pred,6.0M y_pred,3.0M y_pred_scaled,6.0M y_pred_scaled,average_prediction,Score ML
ISIN,,,,,,,,,,,,,,,,,,,,,
AN8068571086,2010-06-30,BJ2HRV-R,66,4.0,12.0,-0.036334,-8.627907,345.111600,0.693660,United States,...,False,False,-0.010622,0.121474,-0.038641,-0.063893,-0.012880,-0.010649,-0.011764,0.539216
AN8068571086,2010-07-31,BJ2HRV-R,67,4.0,12.0,-0.036334,-8.627907,345.111600,0.693660,United States,...,False,False,0.059924,0.117160,-0.034904,-0.033801,-0.011635,-0.005633,-0.008634,0.737705
AN8068571086,2010-08-31,BJ2HRV-R,68,4.0,12.0,-0.036334,-8.627907,345.111600,0.693660,United States,...,False,False,0.214901,0.191746,0.000113,0.010182,0.000038,0.001697,0.000867,4.128289
AN8068571086,2010-09-30,BJ2HRV-R,69,4.0,12.0,-0.033048,-17.993290,539.503800,0.693660,United States,...,False,False,0.139329,0.092561,0.019639,0.033684,0.006546,0.005614,0.006080,8.314239
AN8068571086,2010-10-31,BJ2HRV-R,70,4.0,12.0,-0.033048,-17.993290,539.503800,0.693660,United States,...,False,False,0.043678,-0.049658,0.022428,0.023445,0.007476,0.003908,0.005692,8.295082
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ZAE000138459,2019-07-31,J9DRN6-R,159276,7.0,5.0,-0.051986,-0.414195,-0.608675,0.636485,None,...,False,False,NaN,NaN,0.002948,0.002050,0.000983,0.000342,0.000662,5.817610
ZAE000138459,2019-08-31,J9DRN6-R,159277,7.0,5.0,-0.051986,-0.414195,-0.608675,0.636485,None,...,False,False,NaN,NaN,0.007936,0.007780,0.002645,0.001297,0.001971,7.137871
ZAE000138459,2019-12-31,J9DRN6-R,159278,7.0,5.0,-0.051986,-0.674326,-1.109643,0.636485,None,...,False,False,NaN,NaN,0.009431,-0.005681,0.003144,-0.000947,0.001098,6.417657
ZAE000138459,2020-01-31,J9DRN6-R,159279,7.0,5.0,-0.051986,-0.674326,-1.109643,0.636485,None,...,False,False,NaN,NaN,0.007830,-0.002178,0.002610,-0.000363,0.001123,6.193772
ZAE000138459,2020-02-29,J9DRN6-R,159280,7.0,5.0,-0.051986,-0.674326,-1.109643,0.636485,None,...,False,False,-0.535132,-0.629058,0.006227,-0.005263,0.002076,-0.000877,0.000599,6.055363

### OTHER

In [4]:
from Codes.ML_PIPELINE import ML_MonthlyProdPipeline

import Config.config_OTHER as config
predictor = ML_MonthlyProdPipeline(  
    config.CONFIG,  
    mode="backtest",
    preprocessing=True,
    update_score_ML=True,
    allow_multiprocessing=False,
    output_path=r"Output_files\\",
    output_file="SCORE_ML_OTHER",
    max_date=today_str
)  

predictor.run()

Start of Preprocressing : (5 min)
Loading data from C:\GoogleDrive\TP\00_screen\screen_aggregate.parquet...
max ecart entre 2 dates :  31.0
min ecart entre 2 dates :  28.0
TEST : detect_if_error_date REUSSI
New Compute Return 3.0started

c:\GoogleDrive\TP\03_ml_enhanced\Codes\ML_PREPROCESS.py:158: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df_sectors = df.reset_index(level=1).groupby(['Date', f'Sector {sector_neutral}']).apply(

New Compute Return 6.0started

c:\GoogleDrive\TP\03_ml_enhanced\Codes\ML_PREPROCESS.py:158: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df_sectors = df.reset_index(level=1).groupby(['Date', f'Sector {sector_neutral}']).apply(

End of Preprocressing.
The preprocessing file is saved at : Input_files\screen_ML_OTHER_backtest.parquet
Debut REPRISE SCORE
Period to predict is : [3.0, 6.0]
Output will be saved at Output_files\\SCORE_ML_OTHER
PRED_2
Period to predict is 3.0M
Number of batches to predict is : 193
No multi processing, sequential method is used for generating backtest...

Backtest 3.0M: 0/193 |          | [00:00<?, ?batch/s]

Period to predict is 6.0M
Number of batches to predict is : 190
No multi processing, sequential method is used for generating backtest...

Backtest 6.0M: 0/190 |          | [00:00<?, ?batch/s]

homogenous_mean_and_rank
Backtesting completed. Results saved to Output_files\\SCORE_ML_OTHER.parquet
Backtesting completed. Results saved to Output_files\\SCORE_ML_OTHER_SHAP.parquet

,Date,Company SEDOL,index,Benchmark ICB Industry,Benchmark ICB Supersector,5Y_Hist EPS TrendStab,5Y_Hist GrossInc TrendStab,5Y_Hist Sales TrendStab,Asset TO exFIN,Benchmark Country English,...,Sector 18,Sector 19,3.0M label,6.0M label,3.0M y_pred,6.0M y_pred,3.0M y_pred_scaled,6.0M y_pred_scaled,average_prediction,Score ML
ISIN,,,,,,,,,,,,,,,,,,,,,
AU0000009771,2018-06-30,NH1WKL-R,0,8.0,14.0,NaN,NaN,108.510000,0.048647,None,...,False,False,NaN,NaN,-0.000347,0.001855,-0.000116,0.000309,0.000097,3.582090
AU0000009771,2018-07-31,NH1WKL-R,1,8.0,14.0,NaN,NaN,63.509920,0.048647,None,...,False,False,NaN,NaN,-0.000967,0.001057,-0.000322,0.000176,-0.000073,2.661738
AU0000009771,2018-08-31,NH1WKL-R,2,8.0,14.0,NaN,NaN,63.509920,0.048647,None,...,False,False,NaN,NaN,0.007341,0.007148,0.002447,0.001191,0.001819,7.513812
AU0000009771,2018-09-30,NH1WKL-R,3,8.0,14.0,NaN,NaN,57.133060,0.048647,None,...,False,False,NaN,NaN,-0.004524,-0.001931,-0.001508,-0.000322,-0.000915,2.185185
AU0000009771,2018-10-31,NH1WKL-R,4,8.0,14.0,NaN,NaN,59.645520,0.048647,None,...,False,False,NaN,NaN,-0.005159,-0.000674,-0.001720,-0.000112,-0.000916,1.904762
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
US69047Q1022,2018-12-31,PRHBD5-R,111075,4.0,12.0,0.373188,4.164956,-17.528850,0.357231,Canada,...,False,False,0.083869,-0.223974,0.016615,0.013376,0.005538,0.002229,0.003884,8.819188
US69047Q1022,2019-06-30,PRHBD5-R,111076,4.0,12.0,13.331340,73.970000,9.291028,0.357231,Canada,...,False,False,-0.092664,-0.143750,-0.002465,-0.005693,-0.000822,-0.000949,-0.000885,1.784387
US69047Q1022,2019-07-31,PRHBD5-R,111077,4.0,12.0,109.242500,478.413800,48.047710,0.357231,Canada,...,False,False,-0.142955,-0.329079,-0.002618,-0.004117,-0.000873,-0.000686,-0.000779,1.813187
ZAE000013181,2025-05-31,DF37H0-R,111078,1.0,3.0,-84.613690,-277.003400,-285.316000,0.640802,South Africa,...,False,False,NaN,NaN,0.000588,0.003953,0.000196,0.000659,0.000427,6.747967
ZAE000138459,2019-03-31,J9DRN6-R,111079,7.0,5.0,0.062550,-0.215650,0.051515,0.636485,None,...,False,False,NaN,NaN,0.003430,0.005728,0.001143,0.000955,0.001049,5.448505

In [2]:
from Codes.ML_PIPELINE import ML_MonthlyProdPipeline

import Config.config_EM as config
predictor = ML_MonthlyProdPipeline(  
    config.CONFIG,  
    mode="backtest",
    preprocessing=True,
    update_score_ML=True,
    allow_multiprocessing=False,
    output_path=r"Output_files\\",
    output_file="SCORE_ML_EM",
    max_date=today_str
)  

predictor.run()

ImportError: Numba needs NumPy 2.0 or less. Got NumPy 2.4.

In [ ]:
from Codes.ML_PIPELINE import ML_MonthlyProdPipeline

import Config.config_US as config_US
import Config.config_EU as config_EU
import Config.config_OTHER as config_OTHER

MODE = "backtest"  # 或 "production"
config_list = [
    config_US,
    config_EU,
    config_OTHER,
]

for config_module in config_list:
    predictor = ML_MonthlyProdPipeline(config_module.CONFIG, mode=MODE)
    predictor.update_screen_aggregate()

Generate Last Screen with ML Score

In [5]:
import pandas as pd

screen = pd.read_parquet(r"C:\GoogleDrive\TP\00_screen\screen_aggregate.parquet")
screen["Date"] = pd.to_datetime(screen["Date"])

last_date = screen["Date"].max()
last_screen = screen[screen["Date"] == last_date]

last_screen.to_parquet(r"C:\GoogleDrive\TP\00_screen\last_screen.parquet")
print(f"Last screen updated, with date as {last_date}.")

Last screen updated, with date as 2026-03-31 00:00:00.

<div style="background-color: #013220; color: white; padding: 10px;">
    <h1> Generation PTF and Backtest</h1>
</div>

In [4]:
from pathlib import Path

import pandas as pd
from Codes.BacktestEngine import *

from tp_core.data_sources import RETURNS_PATH as CANONICAL_RETURNS_PATH
from tp_core.data_sources import SCREEN_AGGREGATE_PATH

path_screen = str(SCREEN_AGGREGATE_PATH)
path_returns = str(CANONICAL_RETURNS_PATH)
list_noire_path = r"\\groupe-ufg.com\Commun\Prive\GestionAM\Ingenierie_Financiere\PROD\_BASE\_ ESG DATA\Liste_Noire_Exclusion.xlsx"


def run_ptf_backtest(
    name,
    bench,
    percentile,
    esg_exclusion,
    ptf_name,
    ponderation="Market cap",
    top_mandatory=None,
    cap_weight_threshold=None,
    cut_mkt_cap=None,
    liste_noire=None,
    score_neutral="ICB 19",
    weight_neutral="ICB 19",
    backtest_col_sector=None,
    sector_neutral=False,
    start_date_floor=None,
    screen_start_date="mois_impair",
    **ptf_builder_extra,
):
    # 统一从更新后的 screen_aggregate 读取，再生成组合和回测
    # ptf_builder_extra：传给 PtfBuilder 的额外参数，如 country_sector_optimize、top_mandatory_by_country 等
    screen_agg_with_score = pd.read_parquet(path_screen)
    returns = pd.read_parquet(path_returns)
    screen_agg_with_score["Date"] = pd.to_datetime(screen_agg_with_score["Date"])
    returns.index = pd.to_datetime(returns.index)

    bench_col = f"Weight in {bench}"
    if bench_col not in screen_agg_with_score.columns:
        raise ValueError(f"screen_aggregate.parquet 中缺少列: {bench_col}")

    # 过滤掉无法在 returns 中找到足够未来交易日的最后几个月，避免回测尾部越界
    return_dates = pd.Index(returns.index.unique()).sort_values()
    return_dates_set = set(return_dates)

    def has_enough_future_returns(date):
        rebalance_date = date + pd.offsets.MonthBegin(1)
        future_dates = return_dates[return_dates > rebalance_date]
        min_future_count = 1 if rebalance_date in return_dates_set else 2
        return len(future_dates) >= min_future_count

    valid_dates = pd.Index(screen_agg_with_score["Date"].drop_duplicates())
    valid_dates = valid_dates[valid_dates.map(has_enough_future_returns)]
    screen_agg_with_score = screen_agg_with_score[
        screen_agg_with_score["Date"].isin(valid_dates)
    ].copy()

    # 只保留该 benchmark 真正存在的日期，避免稀疏历史导致空组合。
    bench_dates = pd.Index(
        screen_agg_with_score.loc[
            screen_agg_with_score[bench_col].fillna(0) > 0, "Date"
        ].drop_duplicates()
    ).sort_values()
    screen_agg_with_score = screen_agg_with_score[
        screen_agg_with_score["Date"].isin(bench_dates)
    ].copy()

    # 回测起点按该 benchmark 自己首次有 Score ML 的日期确定。
    start_date = screen_agg_with_score.loc[
        (screen_agg_with_score[bench_col].fillna(0) > 0)
        & screen_agg_with_score["Score ML"].notna(),
        "Date"
    ].min()
    if pd.isna(start_date):
        raise ValueError(f"{bench} 中没有可用的 Score ML。")

    # 与 generic_histo_seclist(start_date=...) 一致：可选下限，不早于 ML/业务约定的连续数据起点
    if start_date_floor is not None:
        start_date = max(start_date, pd.to_datetime(start_date_floor))

    ptf_save_path = rf"Portfolio_BT\PTF_ESG_{name}.parquet"
    perf_save_path = rf"Portfolio_BT\Perf_ESG_{name}.parquet"
    list_exclusion_save_path = rf"Portfolio_BT\list_exclusion_{name}.parquet"

    builder = PtfBuilder(
        screen_agg_with_score,
        returns,
        bench=bench,
        ptf_name=ptf_name,
        percentile=percentile,
        esg_exclusion=esg_exclusion,
        liste_noire=liste_noire,
        metrics="Score ML",
        ponderation=ponderation,
        top_mandatory=top_mandatory,
        cap_weight_threshold=cap_weight_threshold,
        cut_mkt_cap=cut_mkt_cap,
        score_neutral=score_neutral,
        weight_neutral=weight_neutral,
        **ptf_builder_extra,
    )

    builder.generic_histo_seclist(
        start_date=start_date,
        freq_rebal=1,
        screen_start_date=screen_start_date,
    )

    # 与 score/weight 中性化一致的分组列；若指定则先跑回测以便 backtest_plot_ptf_bench 复用 perf_ptf
    if backtest_col_sector is not None:
        builder.backtest(
            builder.sec_list_historical,
            col_sector=backtest_col_sector,
            sector_neutral=sector_neutral,
        )

    builder.sec_list_historical.to_parquet(ptf_save_path)
    if builder.list_exclusion_histo is not None:
        builder.list_exclusion_histo.to_parquet(list_exclusion_save_path)

    builder.backtest_plot_ptf_bench(save_path=False)
    if builder.perf_ptf is not None:
        perf_to_save = builder.perf_ptf
        if isinstance(perf_to_save, pd.Series):
            perf_to_save = perf_to_save.rename("Perf PTF").to_frame()
        perf_to_save.to_parquet(perf_save_path)

    print(f"{name} backtest saved to {ptf_save_path} and {perf_save_path}")
    return builder

In [7]:
################ EUROPE ################

builder_EU = run_ptf_backtest(
    name="EU",
    bench="STOXX EUROPE 600",
    percentile=0.05,
    esg_exclusion=0,
    ptf_name="ML EU Q1",
    ponderation="Market cap",
    top_mandatory=5,
    cap_weight_threshold=None,
    cut_mkt_cap=0,
    liste_noire=None,
)

Premiere date du screen_agg prise en compte :  2010-07-31 00:00:00

Generating security lists: 100%|██████████| 191/191 [00:26<00:00,  7.20it/s]

Historical sec list is generated, you can check 'self.sec_list_historical' attribute for more details.
Historical exclusion list is generated, you can check 'self.list_exclusion' attribute for more details.
Performance of sec_list is calculated, please check attribute "self.perf_ptf" for more details
Performance of benchmark is calculated, please check attribute "self.perf_bench" for more details

EU backtest saved to Portfolio_BT\PTF_ESG_EU.parquet and Portfolio_BT\Perf_ESG_EU.parquet

### US

In [8]:
################ US ################

builder_US = run_ptf_backtest(
    name="US",
    bench="SP500",
    percentile=0.05,
    esg_exclusion=0,
    ptf_name="ML US Q1",
    ponderation="Market cap",
    top_mandatory=5,
    cap_weight_threshold=None,
    cut_mkt_cap=None,
    liste_noire=None,
)

Premiere date du screen_agg prise en compte :  2010-07-31 00:00:00

Generating security lists: 100%|██████████| 191/191 [00:24<00:00,  7.80it/s]

Historical sec list is generated, you can check 'self.sec_list_historical' attribute for more details.
Historical exclusion list is generated, you can check 'self.list_exclusion' attribute for more details.
Performance of sec_list is calculated, please check attribute "self.perf_ptf" for more details
Performance of benchmark is calculated, please check attribute "self.perf_bench" for more details

US backtest saved to Portfolio_BT\PTF_ESG_US.parquet and Portfolio_BT\Perf_ESG_US.parquet

### Other

In [9]:
################ OTHER ################

builder_OTHER = run_ptf_backtest(
    name="OTHER",
    bench="Univ ML OTHER",
    percentile=0.05,
    esg_exclusion=0.2,
    ptf_name="ML OTHER Q1",
    ponderation="Market cap",
    top_mandatory=5,
    cap_weight_threshold=None,
    cut_mkt_cap=2000,
    liste_noire=None,
)

Premiere date du screen_agg prise en compte :  2010-07-31 00:00:00

Generating security lists: 100%|██████████| 191/191 [00:22<00:00,  8.48it/s]

Historical sec list is generated, you can check 'self.sec_list_historical' attribute for more details.
Historical exclusion list is generated, you can check 'self.list_exclusion' attribute for more details.
Performance of sec_list is calculated, please check attribute "self.perf_ptf" for more details
Performance of benchmark is calculated, please check attribute "self.perf_bench" for more details

OTHER backtest saved to Portfolio_BT\PTF_ESG_OTHER.parquet and Portfolio_BT\Perf_ESG_OTHER.parquet

In [2]:
################ EM ################
# 先运行上方定义 run_ptf_backtest 的单元格。country_sector_optimize=True 需 pip install cvxpy

builder_EM = run_ptf_backtest(
    name="EM",
    bench="MSCI EM",
    percentile=0.2,
    esg_exclusion=0.2,
    ptf_name="ML EM Q1",
    ponderation="Market cap",
    cap_weight_threshold=None,
    cut_mkt_cap=2000,
    liste_noire=None,
    score_neutral="ICB 19",
    weight_neutral="ICB 19",
    # sector_neutral=True,
    start_date_floor="2010-07-31",
    top_mandatory_by_country=True,
    top_mandatory=2,
    country_sector_optimize=True,
)

Premiere date du screen_agg prise en compte :  2013-09-30 00:00:00

Generating security lists: 100%|██████████| 120/120 [00:11<00:00, 10.13it/s]

Historical sec list is generated, you can check 'self.sec_list_historical' attribute for more details.
Historical exclusion list is generated, you can check 'self.list_exclusion' attribute for more details.
Performance of sec_list is calculated, please check attribute "self.perf_ptf" for more details
Performance of benchmark is calculated, please check attribute "self.perf_bench" for more details

EM backtest saved to Portfolio_BT\PTF_ESG_EM.parquet and Portfolio_BT\Perf_ESG_EM.parquet

In [5]:
builder_EM.sec_list_historical.to_parquet(r"ptf_em.parquet")

<div style="background-color: #013220; color: white; padding: 10px;">
    <h1> Rassemblage</h1>
</div>

In [ ]:

from pathlib import Path

ptf_eu_path = Path(r"Portfolio_BT\PTF_ESG_EU_semi.parquet")
if not ptf_eu_path.exists():
    ptf_eu_path = Path(r"Portfolio_BT\PTF_ESG_EU.parquet")

PTF_EU = pd.read_parquet(ptf_eu_path)
PTF_US = pd.read_parquet(r"Portfolio_BT\PTF_ESG_US.parquet")
PTF_OTHER = pd.read_parquet(r"Portfolio_BT\PTF_ESG_OTHER.parquet")

# Verifier qu'on a la meme dates
dates_sont_egales(PTF_EU, PTF_US, PTF_OTHER)

Les dates sont les mêmes

In [ ]:
returns = pd.read_parquet(path_returns) 
screen_agg = pd.read_parquet(path_screen)
screen_agg = screen_agg.reset_index()

In [ ]:

# POIDS REGIONAUX DANS ACWI 
weight_regions_acwi = (
screen_agg
.groupby('Date')
.apply(compute_weights_for_date_acwi)
)

# REBALANCE 100%
weight_regions_acwi = weight_regions_acwi.div(weight_regions_acwi.sum(axis=1), axis=0)

# POIDS REGIONAUX DANS MSCI WORLD after 2017
weight_regions_world = (
screen_agg[screen_agg['Date']>="2017-01-01"]
.groupby('Date')
.apply(compute_weights_for_date_world)
)

# REBALANCE 100%
weight_regions_world = weight_regions_world.div(weight_regions_world.sum(axis=1), axis=0)


# Replace weight after 2017 with MSCI WORLD data
weight_regions_acwi.loc[weight_regions_world.index, ['US weight', 'EU weight', 'Other weight']] = weight_regions_world[['US weight', 'EU weight', 'Other weight']]
weight_regions_bench = weight_regions_acwi.copy(deep=True)

# Align date of regional weight with date of ptf generated
weight_regions_bench.index = weight_regions_bench.index + pd.offsets.MonthBegin(1) # Both regional weight or ptf will have the first day of month as Date


# SOUS PONDERER OTHER DE 0.8
weight_regions_bench = adjust_weights_OTHER(weight_regions_bench, ratio_other=0.8)


us_adjusted = adjust_single_portfolio_weights(PTF_US, weight_regions_bench.reset_index(), 'US')
eu_adjusted = adjust_single_portfolio_weights(PTF_EU, weight_regions_bench.reset_index(), 'EU')
other_adjusted = adjust_single_portfolio_weights(PTF_OTHER, weight_regions_bench.reset_index(), 'Other')

ptf_world_semi = pd.concat([us_adjusted, eu_adjusted, other_adjusted], axis=0)
ptf_world_semi = ptf_world_semi[ptf_world_semi['Date'] >= "2010-03-01"]

# Rebalancing
ptf_world_semi['Weight'] = (
                    ptf_world_semi.groupby(["Date"])['Weight']
                    .transform(lambda w: w / w.sum())
                    )


world_ptf_save_path_parquet = r"Portfolio_BT\PTF_WORLD_semi.parquet"
ptf_world_semi.to_parquet(world_ptf_save_path_parquet)
world_ptf_save_path_excel = r"Portfolio_BT\PTF_WORLD_semi.xlsx"
ptf_world_semi.to_excel(world_ptf_save_path_excel)

perf_save_path = rf"Portfolio_BT\Perf_ESG_WORLD_semi.parquet"
bench = "MSCI ACWI"

perf_ptf_WORLD_semi, perf_bench_WORLD_semi, buy_list = generate_portfolio_performance(
    screen_agg, ptf_world_semi, bench, returns, perf_save_path
)

perf_WORLD_semi = normalize_to_base_100(pd.concat([perf_ptf_WORLD_semi, perf_bench_WORLD_semi], axis=1).dropna())